server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.web: DEBUG
    com.danielparra.licenseservice: DEBUG
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/auth/user